- magmi/engines/magmi_productimportengine.php
This should do the following:
TODO:
I'm not sure if this is correct, but this is a partial PR for #176
> Prevent duplicate option value entries

- magmi/inc/magmi_engine.php
The default dir is '../..', which will lead to an incorrect path. Throw a more helpful exception when the path is not found.
> Fix local.xml path

- magmi/engines/magmi_productimportengine.php
- magmi/inc/magmi_engine.php
- magmi/plugins/base/itemprocessors/configurables/magmi_configurableprocessor.php
- magmi/plugins/inc/magmi_defaultattributehandler.php
- magmi/plugins/utilities/clearproductsandcategories/clearproductsandcategories.php
Using strings to compare versions isn't very reliable. Especially because we are currently at '1.9.x'. If you string compare that with '1.10.x', php thinks that 1.9.x > 1.10.x.
PHP has a built-in [version_compare function](http://php.net/manual/en/function.version-compare.php) that accounts for this. This PR adds a method to check the Magento version against a given version + operator.
> Use version_compare to check magento version

- magmi/plugins/extra/itemprocessors/imageprocessor/options_panel.php
magmi. prefix now changed to meta. but not updated in tips so tips shown give invalid examples.
Also changed final example rename string, as it does not help where gallery column contains multiple images with the same filename (as the directory they are stored in is lost during import, so magento overwrites previous image). New example now simply generates iterative filenames for all images which are unique, ignoring original filename (keeps extension)
> Update image preprocessor rename options help

- magmi/plugins/extra/itemprocessors/groupprice/grouppriceprocessor.php
I noticed a select on the tax_class breaking, also the group name was case sensitive so just added some UPPER() and strtoupper() for cleanliness
> Fix table name on tax_class, made group name not case sensitive

- magmi/plugins/extra/itemprocessors/downloadable/downloadableprocessor.php
The downloadable_link table was hard coded, so threw an error if your DB tables have a prefix.
> Fixing hard coded table name

- magmi/engines/magmi_productimportengine.php
- magmi/plugins/extra/itemprocessors/itemindexer/otfindexer.php
New pull request: now based on current master HEAD.
Magmi gets really slow when having a huge set of attributes (which spread across a huge number of attribute sets, each set only having a couple of attributes in my case).
I added some performance tweaks, the most significant being to only process user defined attributes which are in the products attribute set.
These changes boost Magmi by factor 20 for my test case (30.000 products, 1000 attributes, 2000 sets having 6-7 attributes each in average)
In this version I also added a new approach for the (new) duplicate check in otfindexer, because the old approach was quite slow.
Please carefully check all changes! I'm not sure if I fully took account of all cases and plugin specialties.
Thanks!
> Performance optimization for huge numbers of attributes

- magmi/web/security.php
This is fix for problem with updating details while imports due to session block.
Other solution is to remove in magmi_progress.php:
```PHP
session_start();
$_SESSION["log_error"] = $errors;
$_SESSION["log_warning"] = $warnings;
session_write_close();
```
**I'm not sure which idea is better.**
> prevents blocking of magmi_progress.php while imports

- composer.json
Not sure if there is any point of installing magmi as magento module but for sure using magmi with pure composer does not require magento-composer-installer and 7 derived dependencies to be downloaded.
Also prompt to define Magento root is breaking the build.
> Remove magento-composer-installer requirement

- magmi/inc/array_reader.php
- magmi/inc/dbhelper.class.php
- magmi/inc/magmi_csvreader.php
- magmi/integration/inc/attributeset_datapump.php
- magmi/integration/inc/pumpfactory.ini
- magmi/plugins/5b5/general/attributesetimport/additional_data_csv_reader.php
- magmi/plugins/5b5/general/attributesetimport/attributesetimport.mediawiki
- magmi/plugins/5b5/general/attributesetimport/attributesetimport.php
- magmi/plugins/5b5/general/attributesetimport/checkbox.php
- magmi/plugins/5b5/general/attributesetimport/csv_options.php
- magmi/plugins/5b5/general/attributesetimport/csvds_filelist.php
- magmi/plugins/5b5/general/attributesetimport/javascript.php
- magmi/plugins/5b5/general/attributesetimport/multi_dim_array.php
- magmi/plugins/5b5/general/attributesetimport/name2id_decoding.php
- magmi/plugins/5b5/general/attributesetimport/options_panel.php
- magmi/plugins/5b5/general/attributesetimport/text.php
- magmi/plugins/5b5/general/attributesetimport/textarea.php
Added a new general plugin that imports attribute, attribute set and set-to-attribute associations from different CSV files while "startup" phase of import.
There is a mediawiki notation file within the plugin dir (magmi/plugins/5b5/general/attributesetimport/attributesetimport.mediawiki) which you could use as documentation page for the plugin.
> added attribute set importer v0.0.1

- magmi/inc/dbhelper.class.php
DBHelper cols() function returned too many columns if there are multiple databases with same table names on the mysql instance.
> Fixed problems when having multiple magento databases on a single mysql instance

- magmi/plugins/5b5/general/attributesetimport/attributesetimport.mediawiki
- magmi/plugins/5b5/general/attributesetimport/attributesetimport.php
* Made Attribute Set Importer update logic more generic, to be able to easier add new functionality for complex fields (like current magmi:groups field) later on.
* New version number, because configuration format has changed a little bit
* Added some warnings to plugin documentation
> Attribute Set Importer v0.0.2: More generic "inner" data handling

- magmi/engines/magmi_productimportengine.php
- magmi/inc/dbhelper.class.php
- magmi/integration/inc/attributeset_datapump.php
- magmi/plugins/5b5/general/atrributescleanup/attributescleanup.mediawiki
- magmi/plugins/5b5/general/atrributescleanup/attributescleanup.php
- magmi/plugins/5b5/general/atrributescleanup/options_panel.php
- magmi/plugins/5b5/general/attributesetimport/attributesetimport.php
- magmi/web/magmi_config_setup.php
This change contains different changes related to the main goal of allowing to update attribute sets on products while import:
* Cleaned up fetchProdEType(), $this->_prod_etype and other methods to obtain the "catalog product" entity type into one single function "getProductEntityType()" (which was already existing before)
* Added attribute set update functionality to productimport engine.
* Added a global configuration option to disable attribute set update (to allow users to simulate old import behavior if needed)
* Added new general plugin "Attribute Cleanup", which removes attributes from products which don't belong to it's attribute set (either after attribute set of product was changed or attribute set itself was changed)
> Allow update of attribute sets on products

- magmi/plugins/base/general/emailreport/emailreport.php
- magmi/plugins/base/general/emailreport/options_panel.php
Hi Seb,
Noticed this feature request on SF, so thought I'd knock it together.
Allows users to request that their csv file and report are zipped (required the PHP zip extension) as part of the email report - will check for existence before allowing them to enable it, but then if enabled will send the report and csv file (if selected) in a zip archive.
Best,
Liam
> Ability to zip up email reports

- magmi/engines/magmi_productimportengine.php
There's no need to check 'is_configurable' attribute. By default in Magento all attributes which can be used to create configurable products MUST be global. You can check this easily in Magento admin, when adding a new attribute - if you change scope the option "Use To Create Configurable Product" will appear/disappear. 
On the other hand, many of the predefined attributes that come with Magento installation, such as "price", for some reason have set 'is_configurable' to 1. This results in a bug where prices get updated only in a default store, but not in the store which is actually stated in the data source, as price is treated as a global attribute.
Issue is described in #265 as well.
> Fixing scope issue with 'is_configurable' attribute setting'

- magmi/plugins/base/itemprocessors/importlimiter/01_importlimiter.php
If the Import Limiter plugin is enabled and the Columns field is left blank, the columns are limited to nothing.  This causes an issue where the import will not continue because the limiter excludes all of the columns.
This is caused by this in the plugin file:
`explode(",", $this->getParam("LIMITER:col_filter"));`
Since `$this->getParam("LIMITER:col_filter")` is empty, `explode()` is returning the following:
Array
(
[0] => 
)
And when the `if(count($this->_col_filter) > 0)` is being done, the value `1` is being returned for `count()` because the array has one key value which is empty.
The solution is to wrap the `explode()` with a `array_filter()` to eliminate all of the blank values.
This behavior and solution for `explode()` is noted by example on the PHP manual here: …
> Item Limiter: blank "Columns" field causes all datasource columns to be excluded from import

- .gitignore
- magmi/inc/magmi_engine.php
Using Magmi with HHVM is currently not possible without this fix.
Also after the fix it is still only usable if you disable authentification in security.php, because HHVM did not support PHP Basic Auth. See here: https://github.com/facebook/hhvm/issues/2560
To disable auth you need to comment out everything inside security.php, but be sure to use something like htaccess for authentification instead to keep magmi secure.
Maybe a better way for magmi would be to use an own login form and not use the one from Basic Auth.
> HHVM Bugfix class Magmi_UtilityEngine could not be converted to string

- README.md
- magmi/web/.htaccess-sample-php_cgi_fpm
- magmi/web/security.php
HTTP Authentication with PHP CGI/FPM is not working, since $_SERVER['PHP_AUTH_USER'] and $_SERVER['PHP_AUTH_PW'] is not set.
Workaround inspired by the Symphony code: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/ServerBag.php#L47
> [FIX] Authentication with PHP CGI/FPM

- magmi/engines/magmi_productimportengine.php
```
$ php magmi/cli/magmi.cli.php                                                                                                                                                                                                               on  master↑2|✚2?
Fatal error: Call to a member function getRecordsCount() on null in gmagmi-git/magmi/engines/magmi_productimportengine.php on line 1626
Call Stack:
0.0002     264920   1. {main}() gmagmi-git/magmi/cli/magmi.cli.php:0
0.0058    1408584   2. Magmi_Engine->run() gmagmi-git/magmi/cli/magmi.cli.php:123
0.0064    1428336   3. Magmi_ProductImportEngine->engineRun() gmagmi-git/magmi/inc/magmi_engine.php:453
0.0178    3208496   4. Magmi_ProductImportEngine->lookup() gmagmi-git/magmi/engines/magmi_productimportengine.php:1843
```
> Exclude Fatal error

- magmi/inc/magmi_engine.php
```
$ php magmi/cli/magmi.cli.php --help                                                                                                                                                                                                           on  devel|✚1?
Notice: Undefined offset: -1 in gmagmi-git/magmi/inc/magmi_engine.php on line 273
Call Stack:
0.0002     265072   1. {main}() gmagmi-git/magmi/cli/magmi.cli.php:0
0.0057    1408120   2. Magmi_Engine->run() gmagmi-git/magmi/cli/magmi.cli.php:123
0.0062    1427872   3. Magmi_ProductImportEngine->engineRun() gmagmi-git/magmi/inc/magmi_engine.php:452
0.0178    3202728   4. Magmi_ProductImportEngine->getDataSource() gmagmi-git/magmi/engines/magmi_productimportengine.php:1841
0.0178    3202832   5. Magmi_Engine->getPluginInstance() …
```
> Exclude "Undefined offset" notice

- magmi/web/js/magmi_utils.js
Parentheses in column mapper column names were getting saved into config keys without encoding and generating errors in parse_ini_file when the config file was subsequently loaded.
> Encode more chars to prevent invalid config keys

- magmi/plugins/5b5/general/atrributescleanup/attributescleanup.php
- magmi/plugins/5b5/general/attributesetimport/additional_data_csv_reader.php
- magmi/plugins/5b5/general/attributesetimport/attributesetimport.php
When I finished installing the magmi into the magento and open the magmi ui page, I found several php errors comes up.
the defination of an array like "$array = []; " wouldn't work due to the PHP version 5.3.19  of my server's.
So I had to change the defination of an array in order to fix the compatibility in PHP 5.3.
Luckly it works well now. 
:)
> fix compatibility of array defination under php5.4

- magmi/plugins/5b5/general/attributesetimport/functions.php
Change default display style of main &lt;div&gt; elements in options panel to "on" to prevent wrong presentation after initial activation of
plugin.
> Enable options correctly on initial activation of attribute(set)importer plugin

- magmi/plugins/extra/itemprocessors/groupprice/grouppriceprocessor.php
This is a priority bug fix if possible. Referencing #199.
> Fix for NOT LOGGED IN group name in grouppriceprocessor

- README.md
Added additional details regarding Apache mod_proxy_fcgi auth/login issues.
Cleaned up and formatted the README using GitHub Markdown.
> Formatted README; Apache mod_proxy_fcgi info

- magmi/plugins/base/itemprocessors/configurables/magmi_configurableprocessor.php
Fixed Configurable plugin bug when mixed products are imported (configurable and simple) in the "options_container".
> Bugfix in configurable item processor plugin

- magmi/engines/magmi_productimportengine.php
When using image items processor, first image is excluded for each products during product re-import (excluded flag is checked). 
Visibly, image processor is waiting for fields in their attribute_id order (i. e. images fields before gallery field).
Patch is to make sure it is always the case.
Explanation :
It happens only when UNQ_EAV_ATTRIBUTE_ENTITY_TYPE_ID_ATTRIBUTE_CODE is used by MySql as key to query eav_attribute database in request.
Database KO (before patch): 
This can be traced to : 
With Mysql EXPLAIN, we have : 
| id | select_type | table                 | type   | possible_keys                                                                    | key                                             | key_len | ref                                    | rows | Extra       | …
> First image can be excluded during magmi re-import with no reason. 

- magmi/plugins/extra/itemprocessors/attributedeleter/attributedeleterprocessor.php
A simple plugin to allow select and multiselect values to be removed in create mode. This should fix #237. To delete values the plugin has to be activated and ````__MAGMI_DELETE__```` has to be supplied as a value to the corresponding attribute.
> Add Attribute Deleter Plugin.

- magmi/plugins/extra/itemprocessors/categories/categoryimport.php
The current recommend and only way of using magmi to create a
category root for each store (not store view) and then through mange
stores assign it there. That means you are forced to create a store for
each language, however the recommended way to make translations of a store is to create a store view for each language.
You cannot set the category root on store view level. So the idea a root
per language doesn't work in this case.
This PR address that by implementing select option style translations
with this syntax:
```
catname::[defaultname] or you could say
danish::[english]
```
Everything works as before in terms of hierarchies:
```
mænd::[men]/sko::[shoes];;kvinder::[women]/sko::[shoes]
```
Basically it just swaps the default name into the first position and
stores the translate …
> Implemented category translations ala select option translations.

- magmi/plugins/inc/magmi_defaultattributehandler.php
#494 - When attribute is multiselect and eav text then save the option ids instead of the fulltext
> #494 - When attribute is multiselect

- magmi/plugins/utilities/clearproducts/clearproduct.php
- magmi/plugins/utilities/clearproductsandcategories/clearproductsandcategories.php
Add truncate for **catalog_product_entity_group_price** table in "Clear Customers, Tags and Wishlists" and "Clear Catalog, Categories and Reviews" utilities.
If you have product with group price and use clean catalog after that you can not reindex.
> Fix Advanced Utilities for Group Price

- magmi/plugins/extra/itemprocessors/categories/categoryimport.php
Fix category product position when base category tree is setted on plugin configuration o some category not have `::x::x::x`
If Base category or some category not have `::x::x::x` set array `$catpos` is not in sync with `$catids` array (see line 375) and category position not working correctly.
Resolve #512
> Fix category product position

- magmi/engines/magmi_productimportengine.php
if ($ovalue !== false && $ovalue != null) returns wrong result in php 5.6.30 and sets $ovalue as false
> null equality issue

- magmi/engines/magmi_productimportengine.php
- magmi/inc/dbhelper.class.php
- magmi/inc/magmi_engine.php
Introduce a new configuration to disable unnecessary product update.
Just set:
```
[MAGENTO]
catalog_product_entity_update = 0
```
in your magmi.ini.
This will prevent Magemi from updating  catalog_product_entity table when not needed e.g. usually magmi updates sku, entity_type_id to the same values as they were before. 
This PR also add logging when beginTransaction or rollback returns false.
This helps debugging deadlock situations
> Add transaction logging and skip catalog_product_entity update config

- magmi/inc/remotefilegetter.php
The condition currently has an incorrect closing parenthesis which causes the parameter to ini_get to be "false". Also with PHP7 ini_get for the "safe_mode" parameter will return a boolean rather than a string. This patch also contains a condition to handle both cases. Both these issues causes remote CSV file downloads that have redirects (i.e. Dropbox) to always fail.
> Obtaining the safe_mode config has incorrect closing parenthesis

- magmi/inc/magmi_utils.php
This PR resolves a PHP 7.4 incompatibility in the `truepath` function.
The following was reported by the [PHP Compatibility Coding Standard for PHP_CodeSniffer](https://github.com/PHPCompatibility/PHPCompatibility) regarding this incompatibility:
FILE: /path/to//magmi/inc/magmi_utils.php
---------------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
---------------------------------------------------------------------------------------------------------------------------------------
97 | WARNING | [x] Curly brace syntax for accessing array elements and string offsets has been deprecated in PHP 7.4. Found: $path{0} …
> Resolve PHP 7.4 incompatibility in the truepath function
