dweeves/magmi-git

magmi/plugins/extra/itemprocessors/itemindexer/otfindexer.php, magmi/plugins/inc/magmi_defaultattributehandler.php
added support for magento EE url key table.
=> fix for import speed & url conflicts.

magmi/plugins/5b5/general/attributesetimport/attributesetimport.mediawiki, magmi/plugins/5b5/general/attributesetimport/attributesetimport.php
Fixed documentation link for Attribute Set Importer and some smaller mistakes on wiki page.
=> Documentation fix

magmi/engines/magmi_productimportengine.php
=> convert some tabs to spaces

magmi/engines/magmi_productimportengine.php
I mixed up a line in the previous PR, it wasn't meant to go in there, sorry!
Here's the bugfix, and then a small other change.
`fetchProdEType` does partly the same as `initProdType`, so I merged that.
=> bugfix + some more changes

magmi/plugins/5b5/general/attributesetimport/additional_data_csv_reader.php
* Bugfix for attribute set importer (there was an error in AdditionalDataCSVReader when using an empty attribute set associations datasource)
=> Fix for empty value set in additional data csv reader

magmi/plugins/extra/itemprocessors/imageprocessor/imageitattributeemprocessor.php
As requested https://github.com/dweeves/magmi-git/issues/329
=> Fix for #329 Wrong image processing in multi-store setup

magmi/inc/magmi_auth.php, magmi/plugins/extra/itemprocessors/groupprice/grouppriceprocessor.php, magmi/web/head.php
Hi Seb,
You quoted an article I wrote a while back with regards using Magento admin authentication within Magmi - you mentioned my patch, but said you'd need to 'de-magento-ise' it.
I've spent a little while doing just that this evening - it basically does the same thing, but the required code to fetch the admin user and check the hash are written into a local class rather than pulling in Magento code.
Don't know if you want to include it as part of the core, as I understand it would break backward-compatibility, but the code is there if you want it!
Best,
Liam
=> Authentication

magmi/plugins/extra/itemprocessors/groupprice/grouppriceprocessor.php
In reference to issue https://github.com/dweeves/magmi-git/issues/327 , this still allows the deletion of the records, as that's the best way to do it, but will re-use those ids where possible rather than always auto-incrementing.
If there are more rows to insert than deleted rows, then it will use new IDs.
=> Updating Group Price to re-use old Ids

composer.json
ADD Symbolic link to the Magmi CLI interface in bin folder.
=> ADD CLI magmi.cli.php to composer bin folder

magmi/plugins/extra/itemprocessors/customoptions/pablo_customoptions.php
=> fixes 'Undefined index: price_type' notice in Custom Options v0.0.7a

magmi/plugins/extra/itemprocessors/imageprocessor/imageitattributeemprocessor.php
=> fix UTF-8 encoding / non-alphanumeric filename handling in Image Attributes Processor

magmi/engines/magmi_productimportengine.php
Fixes https://github.com/dweeves/magmi-git/issues/485
=> Check for category position before preparing for database insertion

magmi/plugins/extra/datasources/itemgenerator/magmi_itemgenerator.php, magmi/plugins/extra/itemprocessors/categories/categoryimport.php
... to keep PHP 5.3 compatibility.
=> Replaced short array syntax

README.md
Hey @dweeves what about setting up a gitter chat for Magmi. Chat about:
- how to use
- how to extend
- how to contribute
- etc.
This PR just adds the gitter chat badge, you'll have to create the chat it self :)
=> Added gitter chat

magmi/plugins/extra/itemprocessors/valuetrim/valuetrimmer.php
mutiselect_sep => multiselect_sep
=> Fix type in multiselect_sep

magmi/web/ajax_gettime.php
=> fixed ajax_gettime.php

magmi/engines/magmi_productimportengine.php
A value of int(0) was being converted to null. This fixes that error.
=> Use strict comparison when comparing values

magmi/inc/magmi_mixin.php
=> Fixed #586

magmi/inc/properties.php
Fixed "Countable error" when $assoc_arr is not an array.
=> Countable error fix

magmi/inc/remotefilegetter.php
Fix issue occurring when product images are provided via cdn url
=> Enable following redirects when downloading resources from url

magmi/plugins/base/general/optimizer/magmi_optimizer_plugin.php
added check if optimization index exists in the table before adding it to prevent error messages in mysql log
=> added check if optimization index exists

composer.json
Fix license name to make packagist happy
=> Update composer.json license

magmi/.htaccess, magmi/cli/.htaccess, magmi/tests/.htaccess
Block access to some files and paths in .htaccess
- all .ini fileas
- all hidden files (starting from dot)
- files from /cli and /tests paths
=> Block access to some files and paths in .htaccess
